name: DDI Access Services CI

on: workflow_dispatch

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 11

  #     - name: Test, package and analyze with maven & SonarCloud
  #       run: mvn -e verify sonar:sonar -Dsonar.projectKey=InseeFr_DDI-Access-Services -Dsonar.organization=inseefr -Dsonar.host.url=https://sonarcloud.io
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Checkout DDI-Access-Services repo
        uses: actions/checkout@v2

      - name: Build with Maven DDI-Access-Services
        run: mvn clean package -DskipTests -B -V --file pom.xml

      - name: Upload war
        uses: actions/upload-artifact@v2
        with:
          name: war
          path: target/*.war
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        id: download
        uses: actions/download-artifact@v2
        with:
          name: war
          path: target/
      - name: Get current version
        id: version
        run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - run: echo ${{steps.version.outputs.prop}}

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: inseefr/ddi-access-services
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: ${{steps.version.outputs.prop}}
