name: DDI Access Services CI

on:
 push:
    branches:
      - dev-postElasticSearch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build with Maven
        run: mvn install --file pom.xml
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/*.jar
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          tags: inseefr/ddi-access-services:elastic

